### ISSUE TITLE
"No controller could be resolved which would match your request."

### ISSUE THREAD

**Issue by timvonwerne** [patriceckhart/NeosRulez.ShoppingCart#2]
Adding any NodeType of this package into Neos produces the following error, each of them with its title of the NodeType.

### Error message

> **An exception was thrown while Neos tried to render your page
> No controller could be resolved which would match your request. Package key: "NeosRulez.ShoppingCart", controller name: "Cart". (GET https://my.website.de/test.html)**
> 
> root<Neos.Fusion:Case>/ documentType<Neos.Fusion:Matcher>/ element<Neos.NodeTypes:Page>/ body<Neos.Fusion:Template>/ content/ main<Neos.Neos:PrimaryContent>/ default<Neos.Fusion:Matcher>/ renderer<Neos.Neos:ContentCollection>/ content<Neos.Neos:ContentCollectionRenderer>/ itemRenderer<Neos.Neos:ContentCase>/ default<Neos.Fusion:Matcher>/ element<NeosRulez.ShoppingCart:Cart><NeosRulez.ShoppingCart:Cart>/`

### Development environment
- Neos 5.0.2

**Comment by patriceckhart** [comment]
Have you set the correct Cart URL in your Sites Package Settings.yaml?

**Comment by timvonwerne** [comment]
I copied the Settings.yaml from here to my Site Package and adjusted it. Now I get this:
`PHP Fatal error:  Declaration of NeosRulez\ShoppingCart\DataSource\OptionsDataSource::getData(?Neos\ContentRepository\Domain\Model\NodeInterface $node, array $arguments) must be compatible with Neos\Neos\Service\DataSource\DataSourceInterface::getData(?Neos\ContentRepository\Domain\Model\NodeInterface $node = NULL, array $arguments = Array) in /var/www/neos/Packages/Plugins/NeosRulez.ShoppingCart/Classes/DataSource/OptionsDataSource.php on line 9`

**Comment by patriceckhart** [comment]
You must create Delivery, Delivercost and Country. After set the identifier in your Settings.yaml and it works. Note: Set all Settings in .yaml.

**Comment by timvonwerne** [comment]
Ah okay, so when the Settings.yaml is correctly filled out, I can create Delivery, Delivercost and Country as NodeTypes?

I'd like to try it out but with the error message noted above, I can't access my site, nor the Neos backend. Any advice for that?

**Comment by patriceckhart** [comment]
No you create the things like delivery, ... and fill the Settings.yaml with your values.

Or send sftp and Neos User/Password via Mail (in my Profile).

**Comment by pascualet** [comment]
Hello Patric,

I have the same problem.

Fatal error: Declaration of NeosRulez\ShoppingCart\DataSource\OptionsDataSource::getData(?Neos\ContentRepository\Domain\Model\NodeInterface $node, array $arguments) must be compatible with Neos\Neos\Service\DataSource\DataSourceInterface::getData(?Neos\ContentRepository\Domain\Model\NodeInterface $node = NULL, array $arguments = Array) in /html/neos/Packages/Plugins/NeosRulez.ShoppingCart/Classes/DataSource/OptionsDataSource.php on line 9

Before installing the plugin I created a page "warenkorb" and adjusted "Settings.yaml". Do I also have to create pages like Delivery, Deliverycost and Country before installing the plugin (it didn't work, after installing the plugin, same error is displayed) or where can I create those things?

Thx for your help.

**Comment by patriceckhart** [comment]
I have pushed version 2.1 now. The problem should be fixed now.

**Comment by timvonwerne** [comment]
Just tried it out for a different project and unfortunately I'm still getting the same array-error. Tried out installation via Packagist but also cloning this repository (although they're both the same versions, but sometimes it helps anyways).. Any idea?

**Comment by patriceckhart** [comment]
I would say the plugins are slowly but surely out of date. If you want to use the new shop plugin, try NeosRulez.Shop. But currently only dev-master is available.
